-- Table: hotel_schema.cleaning

-- DROP TABLE IF EXISTS hotel_schema.cleaning;

CREATE TABLE IF NOT EXISTS hotel_schema.cleaning
(
    cleaning_date date NOT NULL,
    room_id integer NOT NULL,
    rent_contract_id integer NOT NULL,
    cleaning_status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    cleaning_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    CONSTRAINT cleaning_pk_4 PRIMARY KEY (cleaning_id),
    CONSTRAINT cleaning_room_room_id_fk FOREIGN KEY (room_id)
        REFERENCES hotel_schema.room (room_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT rent_contract_id_cleaning___fk FOREIGN KEY (rent_contract_id)
        REFERENCES hotel_schema.contract (contract_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT check_cleaning_date CHECK (cleaning_date > '2020-01-01'::date),
    CONSTRAINT check_cleaning_status CHECK (cleaning_status::text = 'to do'::text OR cleaning_status::text = 'done'::text),
    CONSTRAINT check_room_id CHECK (room_id > 0),
    CONSTRAINT check_rent_contract_id CHECK (rent_contract_id > 0)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS hotel_schema.cleaning
    OWNER to postgres;