-- Table: hotel_schema.contract

-- DROP TABLE IF EXISTS hotel_schema.contract;

CREATE TABLE IF NOT EXISTS hotel_schema.contract
(
    contract_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employee_id integer NOT NULL,
    salary integer NOT NULL,
    conclusive_date date NOT NULL,
    terminate_date date,
    hotel_id integer NOT NULL,
    CONSTRAINT contract_pk PRIMARY KEY (contract_id),
    CONSTRAINT contract_pk_3 UNIQUE (employee_id),
    CONSTRAINT rent_contract_employee_employee_id_fk FOREIGN KEY (employee_id)
        REFERENCES hotel_schema.employee (employee_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT rent_contract_hotel_profile_hotel_id_fk FOREIGN KEY (hotel_id)
        REFERENCES hotel_schema.hotel_profile (hotel_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT check_salary CHECK (salary > 0),
    CONSTRAINT check_employee_id CHECK (employee_id > 0),
    CONSTRAINT check_dates CHECK (conclusive_date < terminate_date),
    CONSTRAINT check_hotel_id CHECK (hotel_id > 0 AND hotel_id < 6)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS hotel_schema.contract
    OWNER to postgres;