-- Table: hotel_schema.employee

-- DROP TABLE IF EXISTS hotel_schema.employee;

CREATE TABLE IF NOT EXISTS hotel_schema.employee
(
    employee_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    full_name character varying(70) COLLATE pg_catalog."default" NOT NULL,
    job character varying(70) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default" NOT NULL,
    hotel_id integer,
    CONSTRAINT employee_pk PRIMARY KEY (employee_id),
    CONSTRAINT employee_hotel_id_fk FOREIGN KEY (hotel_id)
        REFERENCES hotel_schema.hotel_profile (hotel_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT check_job CHECK (job::text ~ '^[A-Za-zА-ЯЁа-яё0-9 -]+$'::text),
    CONSTRAINT check_full_name CHECK (full_name::text ~ '^[A-Za-zА-ЯЁа-яё -]+$'::text),
    CONSTRAINT check_phone CHECK (phone::text ~ '^[0-9]+$'::text)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS hotel_schema.employee
    OWNER to postgres;