-- Table: hotel_schema.guest

-- DROP TABLE IF EXISTS hotel_schema.guest;

CREATE TABLE IF NOT EXISTS hotel_schema.guest
(
    guest_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    phone character varying(20) COLLATE pg_catalog."default",
    full_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    home_address character varying(70) COLLATE pg_catalog."default" NOT NULL,
    reservation_status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    reserved_room_id integer NOT NULL,
    passport character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT guest_pk PRIMARY KEY (guest_id),
    CONSTRAINT passport_uk UNIQUE (passport),
    CONSTRAINT check_reservation_status CHECK (reservation_status::text = 'reserves'::text OR reservation_status::text = 'rents'::text OR reservation_status::text = 'left'::text),
    CONSTRAINT check_phone CHECK (phone::text ~ '^[0-9]+$'::text),
    CONSTRAINT check_guest_full_name CHECK (full_name::text ~ '^[A-Za-zА-ЯЁа-яё -]+$'::text),
    CONSTRAINT check_home_address CHECK (home_address::text ~ '^[A-Za-zА-ЯЁа-яё0-9.,/ -]+$'::text),
    CONSTRAINT check_passport CHECK (passport::text ~ '^[0-9 ]+$'::text)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS hotel_schema.guest
    OWNER to postgres;