-- Table: hotel_schema.hotel_profile

-- DROP TABLE IF EXISTS hotel_schema.hotel_profile;

CREATE TABLE IF NOT EXISTS hotel_schema.hotel_profile
(
    hotel_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    address character varying(100) COLLATE pg_catalog."default" NOT NULL,
    hotel_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT hotel_profile_pk PRIMARY KEY (hotel_id),
    CONSTRAINT check_hotel_id CHECK (hotel_id > 0),
    CONSTRAINT check_phone CHECK (phone::text ~ '^[0-9]+$'::text),
    CONSTRAINT check_address CHECK (address::text ~ '^[A-Za-zА-ЯЁа-яё0-9/., -]+$'::text)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS hotel_schema.hotel_profile
    OWNER to postgres;