-- Table: hotel_schema.room_type

-- DROP TABLE IF EXISTS hotel_schema.room_type;

CREATE TABLE IF NOT EXISTS hotel_schema.room_type
(
    type_code integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    comodity_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    person_capacity integer NOT NULL,
    base_price bigint,
    CONSTRAINT room_type_pk PRIMARY KEY (type_code),
    CONSTRAINT check_comodity_type CHECK (comodity_type::text = ANY (ARRAY['single luxury'::character varying, 'single base'::character varying, 'double luxury'::character varying, 'double base'::character varying, 'queen luxury'::character varying, 'queen base'::character varying]::text[])),
    CONSTRAINT check_person_capacity CHECK (person_capacity = ANY (ARRAY[1, 2])),
    CONSTRAINT check_type_code CHECK (type_code > 0),
    CONSTRAINT check_base_price CHECK (base_price >= 50000 AND base_price <= 400000)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS hotel_schema.room_type
    OWNER to postgres;