-- Table: hotel_schema.room

-- DROP TABLE IF EXISTS hotel_schema.room;

CREATE TABLE IF NOT EXISTS hotel_schema.room
(
    room_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cleaning_status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    capacity_status character varying(20) COLLATE pg_catalog."default" NOT NULL,
    hotel_id integer NOT NULL,
    type_code integer NOT NULL,
    room_number integer,
    CONSTRAINT room_pk PRIMARY KEY (room_id),
    CONSTRAINT room_hotel_profile_hotel_id_fk FOREIGN KEY (hotel_id)
        REFERENCES hotel_schema.hotel_profile (hotel_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT room_room_type_type_code_fk FOREIGN KEY (type_code)
        REFERENCES hotel_schema.room_type (type_code) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT check_room_id CHECK (room_id > 0 AND room_id <= 2000),
    CONSTRAINT check_capacity_status CHECK (capacity_status::text = ANY (ARRAY['free'::character varying, 'busy'::character varying]::text[])),
    CONSTRAINT check_hotel_id CHECK (hotel_id >= 1 AND hotel_id <= 5),
    CONSTRAINT check_cleaning_status CHECK (cleaning_status::text = 'to do'::text OR cleaning_status::text = 'done'::text)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS hotel_schema.room
    OWNER to postgres;