-- Table: hotel_schema.sale

-- DROP TABLE IF EXISTS hotel_schema.sale;

CREATE TABLE IF NOT EXISTS hotel_schema.sale
(
    sale_percent integer NOT NULL,
    end_date date NOT NULL,
    start_date date NOT NULL,
    type_code integer NOT NULL,
    sale_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    CONSTRAINT sale_pk PRIMARY KEY (sale_id),
    CONSTRAINT sale_room_type_type_code_fk FOREIGN KEY (type_code)
        REFERENCES hotel_schema.room_type (type_code) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT check_sale_dates CHECK (start_date <= end_date),
    CONSTRAINT check_sale_sum CHECK (sale_percent >= 0 AND sale_percent <= 50)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS hotel_schema.sale
    OWNER to postgres;