version: '3.8'
networks:
  lab3_network:
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: educational_db
    ports:
      - "5432:5432"
    networks:
      lab3_network:
        aliases:
          - db
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
    ports:
      - "5050:80"
    volumes:
      - ./pg-admin:/var/lib/pgadmin
    networks:
      lab3_network:
        aliases:
          - pgadmin