insert into publishing_house (id_publishing_house, compilers, name) values (1, 'Manuel Buesden', 'Penguin Books');
insert into publishing_house (id_publishing_house, compilers, name) values (2, 'Darya Zellick', 'Vintage Books');
insert into publishing_house (id_publishing_house, compilers, name) values (3, 'Teodor O'' Donohoe', 'Penguin Books');
insert into publishing_house (id_publishing_house, compilers, name) values (4, 'Ofella Sweetlove', 'Hachette Book Group');
insert into publishing_house (id_publishing_house, compilers, name) values (5, 'Talyah Vondrach', 'HarperCollins');
insert into publishing_house (id_publishing_house, compilers, name) values (6, 'Wald Lewton', 'Macmillan');
insert into publishing_house (id_publishing_house, compilers, name) values (7, 'Lorettalorna Kerrane', 'HarperCollins');
insert into publishing_house (id_publishing_house, compilers, name) values (8, 'Valentia MacMoyer', 'Hachette Book Group');
insert into publishing_house (id_publishing_house, compilers, name) values (9, 'Doretta Greenwood', 'Knopf Doubleday Publishing Group');
insert into publishing_house (id_publishing_house, compilers, name) values (10, 'Emmalynn Briar', 'HarperCollins');
insert into publishing_house (id_publishing_house, compilers, name) values (11, 'Bearnard Anstey', 'Penguin Books');
insert into publishing_house (id_publishing_house, compilers, name) values (12, 'Em Ondracek', 'Macmillan');
insert into publishing_house (id_publishing_house, compilers, name) values (13, 'Aubry Metham', 'Bloomsbury Publishing');
insert into publishing_house (id_publishing_house, compilers, name) values (14, 'Guenna Cherrington', 'Straus and Giroux');
insert into publishing_house (id_publishing_house, compilers, name) values (15, 'Mylo Gilding', 'Simon & Schuster');
insert into publishing_house (id_publishing_house, compilers, name) values (16, 'Kettie Mainz', 'Straus and Giroux');
insert into publishing_house (id_publishing_house, compilers, name) values (17, 'Avery Dennington', 'Hachette Book Group');
insert into publishing_house (id_publishing_house, compilers, name) values (18, 'Padraic Besset', 'Knopf Doubleday Publishing Group');
insert into publishing_house (id_publishing_house, compilers, name) values (19, 'Vicky Southall', 'Bloomsbury Publishing');
insert into publishing_house (id_publishing_house, compilers, name) values (20, 'Julina Smetoun', 'Penguin Random House');
insert into publishing_house (id_publishing_house, compilers, name) values (21, 'Kania Jonuzi', 'Knopf Doubleday Publishing Group');
insert into publishing_house (id_publishing_house, compilers, name) values (22, 'Luis Blagdon', 'Knopf Doubleday Publishing Group');
insert into publishing_house (id_publishing_house, compilers, name) values (23, 'Lynnett Mayoral', 'Hachette Book Group');
insert into publishing_house (id_publishing_house, compilers, name) values (24, 'Fallon Tape', 'Farrar');
insert into publishing_house (id_publishing_house, compilers, name) values (25, 'Sax D''eathe', 'Straus and Giroux');
insert into publishing_house (id_publishing_house, compilers, name) values (26, 'Kristien Kytley', 'Penguin Books');
insert into publishing_house (id_publishing_house, compilers, name) values (27, 'Jasen Dabrowski', 'Hachette Book Group');
insert into publishing_house (id_publishing_house, compilers, name) values (28, 'Milly Drains', 'Penguin Random House');
insert into publishing_house (id_publishing_house, compilers, name) values (29, 'Louis Mugford', 'Farrar');
insert into publishing_house (id_publishing_house, compilers, name) values (30, 'Concettina Abberley', 'Penguin Books');
